name: quick_search
description: Multi-platform quick search app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  flutter/services: ^0.0.0

flutter:
  uses-material-design: true